### ISSUE TITLE
Update to Node 16 

### ISSUE THREAD

**Issue by tpimh** [yobasystems/alpine-nodejs#2]
Thank you very much for such a great container!

I think it's time for a small update.

**Comment by tpimh** [comment]
As of today, the latest LTS version is [node-v16.14.2](https://nodejs.org/download/release/latest-v16.x/node-v16.14.2.tar.gz) and current [node-v18.0.0](https://nodejs.org/download/release/latest-v18.x/node-v18.0.0.tar.gz). Furthermore, v12 will reach it's EOL in the end of month.

**Comment by dominictayloruk** [comment]
Update for you sir. Enjoy!

**Comment by tpimh** [comment]
Hi @dominictayloruk!

It looks like on [dockerhub](https://hub.docker.com/r/yobasystems/alpine-nodejs/tags) only the "min" tags got updated, but "current" and "lts" still have the old versions.

**Comment by dominictayloruk** [comment]
They seem to be timing out on the builds, arm & arm64 seem to be the culprit. These are are built on Raspberry Pi 4s maybe need to look at something more powerful.
